name: "🚀 Release with UV"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: "📥 Checkout repository"
      uses: actions/checkout@v4

    - name: "⚡ Install UV"
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        export PATH="$HOME/.cargo/bin:$PATH"

    - name: "🐍 Set up Python"
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        uv python install 3.11

    - name: "📋 Install Task"
      uses: arduino/setup-task@v2
      with:
        version: 3.x

    - name: "✅ Verify UV Installation"
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "UV version:"
        uv --version
        echo "UV Python installations:"
        uv python list

    - name: "📦 Setup project with UV"
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        uv sync --all-groups

    - name: "🏗️ Build package with UV"
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        uv build

    - name: "✅ Check package"
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        uv run twine check dist/*

    - name: "📤 Publish to TestPyPI"
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - name: "🎉 Publish to PyPI"
      if: startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: "🏷️ Create GitHub Release"
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false